# Generated by Django 5.2.4 on 2026-03-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0001_initial"),
    ]

    operations = []
