# Generated by Django 4.2.7 on 2026-03-14 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0002_auto_20260314_0921"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemDeptInfo",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="4bea435738cc4406bf3e605d7bf7da42",
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode_type",
                    models.SmallIntegerField(default=0, verbose_name="模式类型"),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="描述"
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="部门名称")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        verbose_name="部门编码",
                    ),
                ),
                ("rank", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "auto_bind",
                    models.BooleanField(default=False, verbose_name="自动绑定"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
            ],
            options={
                "verbose_name": "部门信息",
                "verbose_name_plural": "部门信息",
                "db_table": "system_deptinfo",
                "ordering": ["rank", "created_time"],
            },
        ),
        migrations.CreateModel(
            name="SystemMenu",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="271b5ec7244e4e5fba2f6e48e901b2a2",
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "menu_type",
                    models.SmallIntegerField(
                        choices=[(0, "目录"), (1, "菜单"), (2, "按钮")],
                        verbose_name="菜单类型",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="菜单名称"
                    ),
                ),
                ("rank", models.IntegerField(default=0, verbose_name="排序")),
                ("path", models.CharField(max_length=255, verbose_name="路由路径")),
                (
                    "component",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="组件路径"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="请求方法"
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单权限",
                "verbose_name_plural": "菜单权限",
                "db_table": "system_menu",
                "ordering": ["rank", "created_time"],
            },
        ),
        migrations.CreateModel(
            name="SystemMenuMeta",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="6b108f7da67b4d4db9aebf8e3d80087a",
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="菜单标题"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="图标"
                    ),
                ),
                (
                    "r_svg_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="SVG图标名称",
                    ),
                ),
                (
                    "is_show_menu",
                    models.BooleanField(default=True, verbose_name="是否显示菜单"),
                ),
                (
                    "is_show_parent",
                    models.BooleanField(default=False, verbose_name="是否显示父级"),
                ),
                (
                    "is_keepalive",
                    models.BooleanField(default=True, verbose_name="是否缓存"),
                ),
                (
                    "frame_url",
                    models.URLField(blank=True, null=True, verbose_name="iframe地址"),
                ),
                (
                    "frame_loading",
                    models.BooleanField(default=False, verbose_name="iframe加载状态"),
                ),
                (
                    "transition_enter",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="进入动画"
                    ),
                ),
                (
                    "transition_leave",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="离开动画"
                    ),
                ),
                (
                    "is_hidden_tag",
                    models.BooleanField(default=False, verbose_name="是否隐藏标签"),
                ),
                (
                    "fixed_tag",
                    models.BooleanField(default=False, verbose_name="固定标签"),
                ),
                (
                    "dynamic_level",
                    models.IntegerField(default=0, verbose_name="动态层级"),
                ),
            ],
            options={
                "verbose_name": "菜单元数据",
                "verbose_name_plural": "菜单元数据",
                "db_table": "system_menumeta",
                "ordering": ["created_time"],
            },
        ),
        migrations.CreateModel(
            name="SystemOperationLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="模块名称"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="请求路径"
                    ),
                ),
                (
                    "body",
                    models.TextField(blank=True, null=True, verbose_name="请求体"),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="请求方法"
                    ),
                ),
                (
                    "ipaddress",
                    models.CharField(
                        blank=True, max_length=39, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="浏览器"
                    ),
                ),
                (
                    "system",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="操作系统"
                    ),
                ),
                (
                    "response_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="响应状态码"
                    ),
                ),
                (
                    "response_result",
                    models.TextField(blank=True, null=True, verbose_name="响应结果"),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="业务状态码"
                    ),
                ),
            ],
            options={
                "verbose_name": "操作记录",
                "verbose_name_plural": "操作记录",
                "db_table": "system_operationlog",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="SystemUserInfoRoles",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "用户角色关联",
                "verbose_name_plural": "用户角色关联",
                "db_table": "system_userinfo_roles",
            },
        ),
        migrations.CreateModel(
            name="SystemUserRole",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="34f9d621a35a4987a99b6dd3a998e15e",
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="角色名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        verbose_name="角色编码",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
            ],
            options={
                "verbose_name": "用户角色",
                "verbose_name_plural": "用户角色",
                "db_table": "system_userrole",
                "ordering": ["created_time"],
            },
        ),
        migrations.CreateModel(
            name="SystemUserRoleMenu",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "角色菜单关联",
                "verbose_name_plural": "角色菜单关联",
                "db_table": "system_userrole_menu",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_time"],
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.RenameField(
            model_name="user",
            old_name="created_at",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="updated_at",
            new_name="updated_time",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="system_user_usernam_493f1b_idx",
            old_name="users_usernam_baeb4b_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="system_user_email_04b8f7_idx",
            old_name="users_email_4b85f2_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="system_user_phone_4dc0a9_idx",
            old_name="users_phone_af6883_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="user",
            name="uid",
        ),
        migrations.AddField(
            model_name="user",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_column="creator_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="描述"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mode_type",
            field=models.SmallIntegerField(default=0, verbose_name="模式类型"),
        ),
        migrations.AddField(
            model_name="user",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_column="modifier_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="修改者",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="昵称"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="头像"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="邮箱"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.IntegerField(default=0, verbose_name="性别"),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=16, verbose_name="手机号"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="system_userinfo",
        ),
        migrations.AddField(
            model_name="systemuserrolemenu",
            name="menu",
            field=models.ForeignKey(
                db_column="menu_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_menus",
                to="persistence.systemmenu",
                verbose_name="菜单",
            ),
        ),
        migrations.AddField(
            model_name="systemuserrolemenu",
            name="userrole",
            field=models.ForeignKey(
                db_column="userrole_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_menus",
                to="persistence.systemuserrole",
                verbose_name="角色",
            ),
        ),
        migrations.AddField(
            model_name="systemuserrole",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_column="creator_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_user_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="systemuserrole",
            name="menus",
            field=models.ManyToManyField(
                related_name="roles",
                through="persistence.SystemUserRoleMenu",
                to="persistence.systemmenu",
                verbose_name="菜单权限",
            ),
        ),
        migrations.AddField(
            model_name="systemuserrole",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_column="modifier_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_user_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="修改者",
            ),
        ),
        migrations.AddField(
            model_name="systemuserinforoles",
            name="userinfo",
            field=models.ForeignKey(
                db_column="userinfo_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="system_user_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="systemuserinforoles",
            name="userrole",
            field=models.ForeignKey(
                db_column="userrole_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="system_user_roles",
                to="persistence.systemuserrole",
                verbose_name="角色",
            ),
        ),
        migrations.AddField(
            model_name="systemoperationlog",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_column="creator_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作者",
            ),
        ),
        migrations.AddField(
            model_name="systemoperationlog",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_column="modifier_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="修改者",
            ),
        ),
        migrations.AddField(
            model_name="systemmenumeta",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_column="creator_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_menu_metas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="systemmenumeta",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_column="modifier_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_menu_metas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="修改者",
            ),
        ),
        migrations.AddField(
            model_name="systemmenu",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_column="creator_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_menus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="systemmenu",
            name="meta",
            field=models.OneToOneField(
                db_column="meta_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu",
                to="persistence.systemmenumeta",
                verbose_name="菜单元数据",
            ),
        ),
        migrations.AddField(
            model_name="systemmenu",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_column="modifier_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_menus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="修改者",
            ),
        ),
        migrations.AddField(
            model_name="systemmenu",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="persistence.systemmenu",
                verbose_name="父级菜单",
            ),
        ),
        migrations.AddField(
            model_name="systemdeptinfo",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_column="creator_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_depts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="systemdeptinfo",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                db_column="dept_belong_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="belong_depts",
                to="persistence.systemdeptinfo",
                verbose_name="归属部门",
            ),
        ),
        migrations.AddField(
            model_name="systemdeptinfo",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_column="modifier_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_depts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="修改者",
            ),
        ),
        migrations.AddField(
            model_name="systemdeptinfo",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="persistence.systemdeptinfo",
                verbose_name="上级部门",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dept",
            field=models.ForeignKey(
                blank=True,
                db_column="dept_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="persistence.systemdeptinfo",
                verbose_name="所属部门",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                db_column="dept_belong_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="belong_users",
                to="persistence.systemdeptinfo",
                verbose_name="归属部门",
            ),
        ),
        migrations.AddIndex(
            model_name="systemuserrolemenu",
            index=models.Index(
                fields=["userrole"], name="system_user_userrol_e03662_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemuserrolemenu",
            index=models.Index(fields=["menu"], name="system_user_menu_id_f05fbf_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="systemuserrolemenu",
            unique_together={("userrole", "menu")},
        ),
        migrations.AddIndex(
            model_name="systemuserrole",
            index=models.Index(fields=["code"], name="system_user_code_5f1c8d_idx"),
        ),
        migrations.AddIndex(
            model_name="systemuserrole",
            index=models.Index(fields=["name"], name="system_user_name_057f47_idx"),
        ),
        migrations.AddIndex(
            model_name="systemuserinforoles",
            index=models.Index(
                fields=["userinfo"], name="system_user_userinf_9d56df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemuserinforoles",
            index=models.Index(
                fields=["userrole"], name="system_user_userrol_620437_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="systemuserinforoles",
            unique_together={("userinfo", "userrole")},
        ),
        migrations.AddIndex(
            model_name="systemoperationlog",
            index=models.Index(
                fields=["creator"], name="system_oper_creator_53708d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemoperationlog",
            index=models.Index(fields=["module"], name="system_oper_module_c961a5_idx"),
        ),
        migrations.AddIndex(
            model_name="systemoperationlog",
            index=models.Index(
                fields=["created_time"], name="system_oper_created_dbd54a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemmenu",
            index=models.Index(fields=["name"], name="system_menu_name_f811c3_idx"),
        ),
        migrations.AddIndex(
            model_name="systemmenu",
            index=models.Index(
                fields=["parent"], name="system_menu_parent__4b9a35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="systemdeptinfo",
            index=models.Index(fields=["code"], name="system_dept_code_09ee64_idx"),
        ),
        migrations.AddIndex(
            model_name="systemdeptinfo",
            index=models.Index(
                fields=["parent"], name="system_dept_parent__e1e8b9_idx"
            ),
        ),
    ]
